### ISSUE TITLE
How to Configure AzureAd Security Realm using JCasC on Kuberentes

### ISSUE THREAD

**Issue by max-blue** [jenkinsci/azure-ad-plugin#582]
### Describe your use-case which is not covered by existing documentation.

There is not documentation on how to configure Azure AD as security using Jenkins Config as Code (JCasC). Currently I am using the config below with no luck 

```
JCasC:
  securityRealm: |-
    azuread:
      clientId: "${client_id]"
      clientSecret: "${client_secret]"
      tenant: "${tenant]"
      cacheduration: 3600
      fromrequest: false
      environmentName: Azure
      disableGraphIntegration: false
      promptAccount: false
      singleLogout: false
```

### Are you interested in contributing to the documentation?

yes

**Comment by timja** [comment]
There is, see https://github.com/jenkinsci/azure-ad-plugin#configuration-as-code-and-job-dsl-support

**Comment by max-blue** [comment]
I followed the documentation provided in the link you sent and crafted the yaml below. My Jenkins master pods are crashing looping with long string of exceptions in the logs that I cannot tell where the error is. See below:

```
JCasC:
        securityRealm: |-
          azureSecurityRealm:
            clientid: "12345678990ABCDEFGHIKJLMNOP123456"
            clientsecret: "${CLIENT_SECRET}"
            tenant: "12345678990ABCDEFGHIKJLMNOP123456"
            cacheduration: 3600
            fromrequest: false
            environmentName: Azure
            disableGraphIntegration: false
            promptAccount: false
            singleLogout: false
        authorizationStrategy: |-
          azureAdMatrix:
            entries:
              - group:
                  name: 0jfh3724-aBCD-9999-56hgj-1234567890
                  permissions:
                    - Overall/Administer
              - group:
                  name: 934884-aBCD-9999-56hgj-0987654321
                  permissions:
                    - View/Read
                    - Job/Cancel
                    - Job/Create
                    - Job/Discover
                    - Job/Read
                    - Job/Workspace   
              - user:
                  name: 689741-EFJH-9999-56hgj-1234567890
                  permissions:
                    - Overall/Administer
              - user:
                  name: kdljdeo8372-LKJHD-0000-56hgj-1234567890
                  permissions:
                    - Job/Build
                    - Job/Cancel
                    - Job/Read
                    - Agent/Connect     
```
